import { Conditions } from '@pandacss/types';

export const conditions: Conditions = {
  open: '&[data-open="true"]',
  closed: '&:not([data-open="true"])',
  expanded: '&[data-expanded="true"]',
  collapsed: '&:not([data-expanded="true"])',
  selected: '&[data-selected="true"]',
  checked: '&[data-checked="true"]',
  unchecked: '&:not([data-checked="true"])',
  indeterminate: '&[data-indeterminate="true"]',
  disabled: '&[data-disabled="true"]',
  active: '&[data-active="true"]',
  hover: '&[data-hover="true"]',
  focus: '&[data-focus="true"]',
  focusVisible: '&[data-focus-visible="true"]',
  invalid: '&[data-invalid="true"]',
  valid: '&:not([data-invalid="true"])',
  readonly: '&[data-readonly="true"]',
  required: '&[data-required="true"]',
  empty: '&[data-empty="true"]',
  filled: '&[data-filled="true"]',
  placeholderShown: '&[data-placeholder-shown="true"]',
  highlighted: '&[data-highlighted="true"]',
  pressed: '&[data-pressed="true"]',
  entering: '&[data-entering="true"]',
  exiting: '&[data-exiting="true"]',
  visible: '&[data-visible="true"]',
  hidden: '&[data-hidden="true"]',
  placementTop: '&[data-placement="top"]',
  placementBottom: '&[data-placement="bottom"]',
  placementLeft: '&[data-placement="left"]',
  placementRight: '&[data-placement="right"]',
};
