import { Conditions } from '@pandacss/types';

export const conditions: Conditions = {
  open: '&[data-state="open"]',
  closed: '&[data-state="closed"]',
  expanded: '&[data-expanded]',
  collapsed: '&:not([data-expanded])',
  selected: '&[data-selected]',
  checked: '&[data-state="checked"]',
  unchecked: '&[data-state="unchecked"]',
  indeterminate: '&[data-state="indeterminate"]',
  disabled: '&[data-disabled]',
  active: '&[data-state="active"]',
  hover: '&[data-hover]',
  focus: '&[data-focus]',
  focusVisible: '&[data-focus-visible]',
  invalid: '&[data-invalid]',
  valid: '&:not([data-invalid])',
  readonly: '&[data-readonly]',
  required: '&[data-required]',
  empty: '&[data-empty]',
  filled: '&[data-filled]',
  placeholderShown: '&[data-placeholder-shown]',
  highlighted: '&[data-highlighted="true"]',
  pressed: '&[data-pressed]',
  entering: '&[data-state="entering"]',
  exiting: '&[data-state="exiting"]',
  visible: '&[data-state="visible"]',
  hidden: '&[data-state="hidden"]',
  placementTop: '&[data-placement="top"]',
  placementBottom: '&[data-placement="bottom"]',
  placementLeft: '&[data-placement="left"]',
  placementRight: '&[data-placement="right"]',
};
