import { palette } from './_tokens';

export const theme = {
  colors: {
    ...palette,
    neutral: palette.zinc200,
    'neutral-hover': palette.zinc200,
    'neutral-subtle': palette.zinc50,
    'on-neutral': palette.zinc600,
    primary: palette.violet700,
    'primary-subtle': palette.violet50,
    'primary-hover': palette.violet800,
    'on-primary': palette.white,
    success: palette.green500,
    'success-hover': palette.green700,
    'success-subtle': palette.green50,
    'on-success': palette.white,
    warning: palette.yellow500,
    'warning-hover': palette.yellow700,
    'warning-subtle': palette.yellow50,
    'on-warning': palette.yellow800,
    danger: palette.red500,
    'danger-hover': palette.red700,
    'danger-subtle': palette.red50,
    'on-danger': palette.white,
    canvas: palette.neutral50,
    'on-canvas': palette.neutral900,
    surface: palette.white,
    'on-surface': palette.neutral900,
    outline: palette.zinc200,
    text: palette.neutral800,
    'text-muted': palette.neutral500,
  },
};
