import { defineSlotRecipe } from '@pandacss/dev';

export const sidebarRecipe = defineSlotRecipe({
  className: 'Sidebar',
  slots: [
    'provider',
    'root',
    'overlay',
    'inset',
    'trigger',
    'header',
    'content',
    'footer',
    'group',
    'groupLabel',
    'groupAction',
    'groupContent',
    'label',
    'menu',
    'menuItem',
    'menuButton',
    'menuAction',
    'menuBadge',
    'menuSub',
    'menuSubItem',
    'menuSubButton',
    'rail',
  ],
  base: {
    provider: {
      display: 'flex',
      minHeight: '100vh',
      width: '100%',
      backgroundColor: 'bg.page',
      color: 'fg.default',
      position: 'relative',
      overflowX: 'hidden',
    },
    root: {
      display: 'flex',
      flexDirection: 'column',
      flexShrink: '0',
      width: 'var(--sidebar-width)',
      minHeight: '100vh',
      backgroundColor: 'bg.raised',
      borderRight: 'border.weak',
      transitionProperty: 'width, transform',
      transitionDuration: 'normal',
      transitionTimingFunction: 'default',
      zIndex: '10',
      '&[data-side="right"]': {
        borderRight: '0',
        borderLeft: 'border.weak',
        order: '2',
      },
      '&[data-collapsible="icon"][data-state="collapsed"]': {
        width: 'var(--sidebar-width-icon)',
      },
      '&[data-collapsible="icon"][data-state="collapsed"] [data-part="label"], &[data-collapsible="icon"][data-state="collapsed"] [data-part="footer"], &[data-collapsible="icon"][data-state="collapsed"] [data-part="groupLabel"], &[data-collapsible="icon"][data-state="collapsed"] [data-part="menuBadge"], &[data-collapsible="icon"][data-state="collapsed"] [data-part="menuAction"]': {
        opacity: '0',
        width: '0',
        overflow: 'hidden',
        pointerEvents: 'none',
      },
      '&[data-collapsible="icon"][data-state="collapsed"] [data-part="header"]': {
        paddingInline: '2',
      },
      '&[data-collapsible="icon"][data-state="collapsed"] [data-part="content"]': {
        paddingInline: '2',
      },
      '&[data-collapsible="offcanvas"][data-state="collapsed"]': {
        width: '0',
        transform: 'translateX(-100%)',
      },
      '&[data-side="right"][data-collapsible="offcanvas"][data-state="collapsed"]': {
        transform: 'translateX(100%)',
      },
      '@media (max-width: 767px)': {
        position: 'fixed',
        insetBlock: '0',
        left: '0',
        width: 'var(--sidebar-width-mobile)',
        maxWidth: 'calc(100vw - 2rem)',
        minHeight: '100dvh',
        boxShadow: 'overlay',
        transform: 'translateX(-100%)',
        '&[data-mobile-open="true"]': {
          transform: 'translateX(0)',
        },
        '&[data-side="right"]': {
          left: 'auto',
          right: '0',
          transform: 'translateX(100%)',
        },
        '&[data-side="right"][data-mobile-open="true"]': {
          transform: 'translateX(0)',
        },
      },
    },
    overlay: {
      display: 'none',
      '@media (max-width: 767px)': {
        position: 'fixed',
        inset: '0',
        backgroundColor: 'bg.inverse/48',
        opacity: '0',
        pointerEvents: 'none',
        transitionProperty: 'opacity',
        transitionDuration: 'normal',
        zIndex: '9',
        '&[data-mobile-open="true"]': {
          display: 'block',
          opacity: '1',
          pointerEvents: 'auto',
        },
      },
    },
    inset: {
      flex: '1',
      minWidth: '0',
      backgroundColor: 'bg.page',
    },
    trigger: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '10',
      height: '10',
      margin: '3',
      borderRadius: 'md',
      color: 'fg.muted',
      backgroundColor: 'transparent',
      border: '0',
      cursor: 'pointer',
      transitionProperty: 'background-color, color, transform',
      transitionDuration: 'fast',
      _hover: {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
      _active: {
        transform: 'scale(0.96)',
      },
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'stroke.primary',
        outlineOffset: '2px',
      },
      '& > svg': {
        width: '5',
        height: '5',
      },
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      minHeight: '12',
      flexShrink: '0',
      padding: 'md',
      fontWeight: 'semibold',
      whiteSpace: 'nowrap',
    },
    content: {
      flex: '1',
      minHeight: '0',
      padding: 'md',
    },
    footer: {
      flexShrink: '0',
      padding: 'md',
      color: 'fg.muted',
      fontSize: 'sm',
      whiteSpace: 'nowrap',
      transitionProperty: 'opacity, width',
      transitionDuration: 'fast',
    },
    group: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      gap: '1',
      paddingBlock: '1',
    },
    groupLabel: {
      display: 'flex',
      alignItems: 'center',
      minHeight: '8',
      paddingInline: '2',
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      textTransform: 'uppercase',
      whiteSpace: 'nowrap',
      transitionProperty: 'opacity, width',
      transitionDuration: 'fast',
    },
    groupAction: {
      position: 'absolute',
      top: '1',
      right: '1',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '8',
      height: '8',
      borderRadius: 'md',
      border: '0',
      backgroundColor: 'transparent',
      color: 'fg.muted',
      cursor: 'pointer',
      _hover: {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
    },
    groupContent: {
      display: 'flex',
      flexDirection: 'column',
      gap: '1',
    },
    label: {
      minWidth: '0',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      transitionProperty: 'opacity, width',
      transitionDuration: 'fast',
    },
    menu: {
      display: 'flex',
      flexDirection: 'column',
      gap: '1',
      margin: '0',
      padding: '0',
      listStyle: 'none',
    },
    menuItem: {
      position: 'relative',
    },
    menuButton: {
      display: 'flex',
      alignItems: 'center',
      gap: '2',
      width: '100%',
      minHeight: '10',
      paddingInline: '2',
      borderRadius: 'md',
      color: 'fg.muted',
      textDecoration: 'none',
      whiteSpace: 'nowrap',
      border: '0',
      backgroundColor: 'transparent',
      fontSize: 'sm',
      fontWeight: 'medium',
      cursor: 'pointer',
      transitionProperty: 'background-color, color, transform',
      transitionDuration: 'fast',
      _hover: {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
      _active: {
        transform: 'scale(0.96)',
      },
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'stroke.primary',
        outlineOffset: '2px',
      },
      '&[data-active="true"], &[aria-current="page"], &.active': {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
      '& > svg': {
        width: '4',
        height: '4',
        flexShrink: '0',
      },
      '& [data-part="label"]': {
        transitionProperty: 'opacity, width',
        transitionDuration: 'fast',
      },
    },
    menuAction: {
      position: 'absolute',
      top: '1',
      right: '1',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '8',
      height: '8',
      borderRadius: 'md',
      border: '0',
      backgroundColor: 'transparent',
      color: 'fg.muted',
      cursor: 'pointer',
      transitionProperty: 'opacity, background-color, color',
      transitionDuration: 'fast',
      _hover: {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
    },
    menuBadge: {
      marginLeft: 'auto',
      minWidth: '6',
      borderRadius: 'full',
      paddingInline: '2',
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      textAlign: 'center',
      transitionProperty: 'opacity, width',
      transitionDuration: 'fast',
    },
    menuSub: {
      margin: '0',
      marginLeft: '5',
      padding: '0',
      paddingLeft: '3',
      listStyle: 'none',
      borderLeft: 'border.weak',
    },
    menuSubItem: {
      position: 'relative',
    },
    menuSubButton: {
      display: 'flex',
      alignItems: 'center',
      minHeight: '8',
      paddingInline: '2',
      borderRadius: 'md',
      color: 'fg.muted',
      textDecoration: 'none',
      fontSize: 'sm',
      _hover: {
        color: 'fg.default',
        backgroundColor: 'fill.hover',
      },
    },
    rail: {
      position: 'absolute',
      top: '0',
      right: '-2',
      width: '4',
      height: '100%',
      border: '0',
      backgroundColor: 'transparent',
      cursor: 'col-resize',
      _after: {
        content: '""',
        position: 'absolute',
        top: '0',
        bottom: '0',
        left: '50%',
        width: '1px',
        backgroundColor: 'transparent',
      },
      _hover: {
        _after: {
          backgroundColor: 'stroke.weak',
        },
      },
      '@media (max-width: 767px)': {
        display: 'none',
      },
    },
  },
});
