name: 'Chromatic - React Aria components'

on:
  push:
    paths:
      - 'packages/react-aria/**'
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm exec nx run react-aria:build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_ARIA }}
          storybookBuildDir: dist/storybook/react-aria
          exitOnceUploaded: true
