name: "Chromatic - Base UI components"

on:
    push:
        paths:
            - "packages/base-ui/**"
        branches-ignore:
            - "dependabot/**"
            - "renovate/**"

jobs:
    chromatic:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm exec nx run base-ui:build-storybook

            - name: Publish to Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_BASE_UI }}
                  storybookBuildDir: dist/storybook/@particles/base-ui
                  exitOnceUploaded: true
