name: 'Chromatic - React components'

on:
  push:
    paths:
      - 'packages/react/**'
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm exec nx run react:build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_REACT }}
          storybookBuildDir: dist/storybook/react
          exitOnceUploaded: true
